%YAML:1.0

images_path : "/home/lacie/Documents/workspace/resources/clomap/south-building/images"
database_path : "/home/lacie/Documents/workspace/resources/clomap/south-building/south-building.db"


SIFTextractor.max_image_size : 3200
SIFTextractor.num_features   : 8024
# 0 for L1_ROOT, 1 for L2, 2 for ROOT_SIFT
SIFTextractor.normalization  : 0

# 0 for sequential match, 1 for brute match, 2 for vacabulary tree match(not support now)
SIFTmatch.match_type :  0
# if descriptor is normalizing, then distance between two descriptors in range [0.0, 2.0].
# so, lower max distance with higher correct matches rate but less number of matcher, vice versa.
SIFTmatch.max_distance : 0.7
# distance_ratio may be from 0.5 to 1.0, lower distance ratio with higher correct matches rate but less number of matcher, vice versa.
SIFTmatch.distance_ratio : 0.8
# 0 for not use cross_check, 1 for use cross_check
SIFTmatch.cross_check : 1


#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Reconstruction.Camera.fx: 2559.68
Reconstruction.Camera.fy: 2559.68
Reconstruction.Camera.cx: 1536
Reconstruction.Camera.cy: 1152

Reconstruction.Camera.k1: -0.0204997
Reconstruction.Camera.k2: 0.0
Reconstruction.Camera.p1: 0.0
Reconstruction.Camera.p2: 0.0



Reconstrction.output_path : "./south-building"
Reconstruction.is_visualization : 1





